name: Publish docker images
on:
  push:

jobs:
  publish-base-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        DEBIAN_VERSION:
          - bookworm
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          login-server: cr.kruhlmann.dev
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build base image
        run: >
          docker build . \
            -f Dockerfile \
            -t cr.kruhlmann.dev/debian:${{ matrix.DEBIAN_VERSION }} \
            --build-arg DEBIAN_VERSION=${{ matrix.DEBIAN_VERSION }} \
      - name: Publish base image
        run: docker push cr.kruhlmann.dev/debian:${{ matrix.DEBIAN_VERSION }}


  build-python-images:
    needs: publish-base-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        DEBIAN_VERSION:
          - bookworm
        PYTHON_VERSION:
          - 3.8
          - 3.9
          - 3.10
          - 3.11
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          login-server: cr.kruhlmann.dev
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build python image
        run: >
          docker build . \
            -f python.Dockerfile \
            -t cr.kruhlmann.dev/debian-${{ matrix.DEBIAN_VERSION }}-python-${{ matrix.PYTHON_VERSION }} \
            --build-arg DEBIAN_VERSION=${{ matrix.DEBIAN_VERSION }} \
            --build-arg PYTHON_VERSION=${{ matrix.PYTHON_VERSION }} \
      - name: Publish python image
        run: docker push cr.kruhlmann.dev/debian-${{ matrix.DEBIAN_VERSION }}-python-${{ matrix.PYTHON_VERSION }}
